#:schema node_modules/wrangler/config-schema.json
name = "jz-sublink-worker"
main = "src/index.js"
compatibility_date = "2024-07-24"
compatibility_flags = ["nodejs_compat"]

kv_namespaces = [
  { binding = "SUBLINK_KV", id = "4c797e4fb2f74e898dd62bf4dbc01157" }
]
